apiVersion: v2
name: arbiter
description: Arbiter is an observing and managing tool for Kubernetes
type: application
version: v0.2
appVersion: v0.1
keywords:
  - observing
  - arbiter
home: https://arbiter.k8s.com.cn
icon: xxxxx
sources:
  - https://github.com/arbiter/arbiter
maintainers:
  - name: nkwangleiGIT
    url: https://github.com/nkwangleiGIT
  - name: Abirdcfly
    url: https://github.com/Abirdcfly
  - name: 0xff-dev
    url: https://github.com/0xff-dev
